### ISSUE TITLE
Interactive demo missing objects files

### ISSUE THREAD

**Issue by eliethesaiyan** [vc-bonn/Teaching_Incompressible_Fluid_Dynamics_to_3D_CNNs#1]
Thank you for a great repo on fluid simulations. I wanted to try it but I couldn't run any simulation(2D worked out great) . It seems the simulation objects(obstacles) are not available under `img/` folder. I would appreciate it a lot if you could provide those, in meantime, I will try the steps you in `readme` of generating my own obstacle.
https://github.com/aschethor/Teaching_Incompressible_Fluid_Dynamics_to_3D_CNNs/blob/d87f648f3f2c708b8b66b72ee44b0133d108068b/setups.py#L10-L15

**Comment by wandeln** [comment]
Hi @eliethesaiyan ,
thanks a lot for your comment!
Indeed, I forgot to take the imgs-folder out of the .gitignore 🙈 
I just uploaded the files and hope that it works now... 😄 
Best, Nils

**Comment by eliethesaiyan** [comment]
Thank you very much @aschethor ,i can confirm it is working now, and `blender_voxelizer.py` helped me creating my own object!
